### ISSUE TITLE
IndexOutOfBoundsException in Indexing more than 67 million points

### ISSUE THREAD

**Issue by varpande** [jchambers/jvptree#9]
Hi jchambers. Thank you for the great library. I run into this issue of not being able to index more than 67 million points. I believe the error is being caused here:

https://github.com/jchambers/jvptree/blob/master/src/main/java/com/eatthepath/jvptree/util/SamplingMedianDistanceThresholdSelectionStrategy.java#L61

You multiply i (index for number of samples, default is 32) by number of points. This multiplication crosses the integer limit (if the number of points are more than 67 million), wraps around and thus points.get() gets an index with a negative value causing an index out of bounds exception. Probably dividing number of points by number of samples first and then multiplying by i would do the trick.

 Could you possibly look into this issue? I am attaching the stack trace here for reference.

```
java.lang.IndexOutOfBoundsException: Index -57824128 out of bounds for length 305574400
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at java.base/java.util.Objects.checkIndex(Objects.java:373)
        at java.base/java.util.ArrayList.get(ArrayList.java:426)
        at com.eatthepath.jvptree.util.SamplingMedianDistanceThresholdSelectionStrategy.getSampledPoints(SamplingMedianDistanceThresholdSelectionStrategy.java:61)
        at com.eatthepath.jvptree.util.SamplingMedianDistanceThresholdSelectionStrategy.selectThreshold(SamplingMedianDistanceThresholdSelectionStrategy.java:43)
        at com.eatthepath.jvptree.VPTreeNode.anneal(VPTreeNode.java:88)
        at com.eatthepath.jvptree.VPTreeNode.<init>(VPTreeNode.java:62)
        at com.eatthepath.jvptree.VPTree.addAll(VPTree.java:286)
```

**Comment by jchambers** [comment]
Well, that's about three orders of magnitude more points than I expected anybody to ever actually use this thing for ;)

I'll look into it.

**Comment by varpande** [comment]
Well 305 million dataset is the maximum that I have at the moment, but I was planning to use even bigger datasets :)
Nevertheless if you need the datasets for testing, let me know!

**Comment by jchambers** [comment]
This should be fixed in #10. Please let me know if you have any questions or concerns!

**Comment by varpande** [comment]
I tested the fix with two datasets containing 83 million points and 305 million points. The fix seems to work great! Thank you Jon!

**Comment by jchambers** [comment]
Cheers, and thanks for following up! I can't put out a new release immediately, but will do so soon.
